// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qPVEcqibOvdO-_xAYFRR2FWJYuapGRQ',
    appId: '1:485024798996:web:381c4641068bfe206b0a01',
    messagingSenderId: '485024798996',
    projectId: 'myfitjourney-d4c5c',
    authDomain: 'myfitjourney-d4c5c.firebaseapp.com',
    storageBucket: 'myfitjourney-d4c5c.firebasestorage.app',
    measurementId: 'G-MMWNXMRSJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUl6qx8c7mqwmmEhVjXlkKqscSCdYU-xE',
    appId: '1:485024798996:android:09a15af0d65777016b0a01',
    messagingSenderId: '485024798996',
    projectId: 'myfitjourney-d4c5c',
    storageBucket: 'myfitjourney-d4c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDibHvOiIPFJsaUhpq1zDGXIDzvYx1HnAY',
    appId: '1:485024798996:ios:69dfe547def895946b0a01',
    messagingSenderId: '485024798996',
    projectId: 'myfitjourney-d4c5c',
    storageBucket: 'myfitjourney-d4c5c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFlutter',
  );
}
